#baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "de-de"
title = "learn ATML3"

[taxonomies]
tag = "tags"
category = "categories"

[params]
  description = "Interactive tutorials about using ATML3. Take five minutes to learn the ATML3 NLG language."
  author = "Frank Feulner"
  GitHubUser = "frank-feulner"
